### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by mrkylesmith** [maxrivett/cse15l-lab-reports#2]
**Bug/Input 1**
- [] Commit screenshot for bug/input 1
- Images are not showing up
- [] Link to test file for bug/input 1
- Provide a live link to your test file input
- [] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [] Commit screenshot for bug/input 2
- [] Link to test file for bug/input 2
- Provide a live link to your test file input
- [] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [] Commit screenshot for bug/input 3
- Images are not showing up
- [] Link to test file for bug/input 3
- Provide a live link to your test file input
- [] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
I cannot view any of the images/screenshots you provided.  Please check the syntax of your markdown images and please submit a regrade request with these changes.  Also make sure you include live links to your test file inputs and detailed descriptions of the command, symptom, and output/bug for each of the three cases. 

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by maxrivett** [comment]
Hi there, 
I understand that you cannot view my images for some reason, and I will fix that. 
But I was wondering what you mean in saying that I do not have links to the test files? I have included all three of them. 
And the symptoms are shown but they are images so I'm assuming that if I can get the images fixed then you will see this too.

**Comment by mrkylesmith** [comment]
Hi Max, 
I see all of your screenshots, links and everything needed now, thanks for fixing that.   Please see your updated score on gradescope.
